version: "3"
name: gitea

x-kraud-ui:
  label: "Gitea - Git server"
  description: |
    Gitea is a painless self-hosted Git service.
    It is similar to GitHub, Bitbucket, and GitLab.
    Gitea is a fork of Gogs.

    See the Gitea Announcement blog post to read about the justification for a fork.

    ## Purpose

    The goal of this project is to provide the easiest, fastest, and most painless way of setting up a self-hosted Git service.

  logo_url: "https://docs.gitea.io/images/gitea.png"
  ext_url: "https://gitea.io/"
  config:
    ingress:
      INGRESS:
        label: "web UI domain"
        description: |
          Domain where the app will be hosted.
          You will need to configure the application to use this domain in the first launch as well
        protocol: "https"
        default: "gitea.*"
        required: true

volumes:
  gitea:
    name: gitea
    driver: "rbd"
  gitea_database:
    name: ${DATABASE-gitea_database}
    driver: "rbd"

services:
  server:
    image: gitea/gitea:1.17.3
    container_name: gitea
    labels:
      - kr.ingress.3000=${INGRESS:-https://gitea.*}
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__server__ROOT_URL=${INGRESS:-https://gitea.*}
    restart: always
    volumes:
      - gitea:/data
    ports:
      - "3000:3000"

  db:
    image: postgres:14
    container_name: gitea_db
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - ${DATABASE-gitea_database}:/var/lib/postgresql/data
