version: "3.9"
name: meilisearch

x-kraud-ui:
  label: "Meilisearch - Search engine"
  description: |
    Meilisearch is a RESTful search API.
    It aims to be a ready-to-go solution for everyone who wants a fast and relevant search experience for their end-users ⚡️🔎

    Efficient search engines often require a significant investment of resources. They are only accessible to companies with the means necessary to develop a bespoke search solution that fits their needs.

    Small-to-medium-sized businesses commonly resort to subpar search engines that incur invisible costs on their user experience and retention due to poor search fulfillment.

    That's why we created Meilisearch: An open source solution accessible to everyone, designed to meet a vast majority of needs. Requiring very little configuration to be installed, yet highly customizable.

    Our solution delivers an instant search experience including typo handling, filters, custom rankings, and many more features. Read on to learn more.

    ## Demo

    ![demo gif](https://docs.meilisearch.com/crates-io-demo.gif)

  post_launch: |
    [Check out the docs](https://docs.meilisearch.com/) to learn how to login to your new MeiliSearch instance.

    `${MEILI_MASTER_KEY}` should be used as the master key for your MeiliSearch instance.

  logo_url: "https://avatars.githubusercontent.com/u/43250847?s=200&v=4"
  ext_url: "https://www.meilisearch.com/"
  config:
    INGRESS:
      kind: "ingress"
      label: "http endpoint"
      description: "http endpoint of meilisearch"
      protocol: "https"
      default: "meili.*"
      required: true
    MEILI_MASTER_KEY:
      kind: "hidden"
      label: master key
      default: "{{ randAlphaNum 32 }}"
      description: "master key for meilisearch"
      required: true

services:
  meili:
    container_name: meili
    image: getmeili/meilisearch:v0.29
    labels:
      - kr.ingress.7700=${INGRESS:-https://meili.*}
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY?master key required}
    volumes:
      - meili-data:/meili_data

volumes:
  meili-data:
    name: meili-data
    driver: "local"
