version: '3.9'
name: nextcloud

x-kraud-ui:
  label: "Nextcloud Hub - Remote collaboration"
  description: |
    Regain control over your data

    Remote collaboration made easy

    - On-premises or cloud
    - Customizable and scaleable
    - No data leaks to third parties

    Hub integrates the four key Nextcloud products Files, Talk, Groupware and Office into a single platform, optimizing the flow of collaboration.

  logo_url: "https://avatars.githubusercontent.com/u/19211038"
  ext_url: "https://nextcloud.com/"
  config:
    INGRESS:
      kind: "ingress"
      label: "web UI domain"
      description: Domain where the app will be hosted.
      protocol: "https"
      default: "nextcloud.*"
      required: true
    DATA_SIZE:
      label: "Storage"
      description: "Size of the shared volume."
      kind: select
      default: 20G
      options:
        - label: "5 GB"
          value: "5G"
          description: "5 GB of disk space"
        - label: "10 GB"
          value: "10G"
          description: "10 GB of disk space"
        - label: "20 GB"
          value: "20G"
          description: "20 GB of disk space"
        - label: "50 GB"
          value: "50G"
          description: "40 GB of disk space"
        - label: "100 GB"
          value: "100G"
          description: "100 GB of disk space"
        - label: "200 GB"
          value: "200G"
          description: "200 GB of disk space"
        - label: "500 GB"
          value: "500G"
          description: "400 GB of disk space"
        - label: "1 TB"
          value: "1T"
          description: "1TB of disk space"
        - label: "2 TB"
          value: "2T"
          description: "2TB of disk space"
    ZONE:
      kind: zone
      default: uca
      label: "Deployment zone"
      description: "Zone where the deployment and volumes will be created"
      required: true


volumes:
  nextcloud:
    driver_opts:
      size: ${DATA_SIZE}
      zone: ${ZONE}

services:
  app:
    container_name: nextcloud
    image: nextcloud:25.0-apache
    restart: always
    labels:
      - kr.ingress.http.80=${INGRESS:-https://nextcloud.*}
      - kr.zone=${ZONE}
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - nextcloud/data:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=eeD2ohghthieL3eino5uXae3
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - OVERWRITEPROTOCOL=https
      - TRUSTED_PROXIES=*

  db:
    container_name: db
    image: postgres:15.3
    restart: always
    labels:
      - kr.zone=${ZONE}
    volumes:
      - nextcloud/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=eeD2ohghthieL3eino5uXae3

