version: "3.9"
name: umami

x-kraud-ui:
  label: "Umami - Analytics platform"
  description: |
    Umami is an open source, privacy-focused alternative to Google Analytics.
    Umami provides you with a powerful web analytics solution that does not violate the privacy of your users.
    Additionally, when you self-host Umami you are in complete control of your data.

    ![umami pic](https://umami.is/images/about-screenshot.png)

  post_launch: |
    [check out the docs](https://umami.is/docs/login) to learn how to login to your new Umami instance.

    Your Umami installation will create a default administrator account with the username admin and the password umami.

    The first thing you will want to do is log in and change your password.

  logo_url: "https://avatars.githubusercontent.com/u/105618662?s=200&v=4"
  ext_url: "https://umami.is/"
  config:
    INGRESS:
      kind: "ingress"
      label: "web interface domain"
      description: "domain where umami will be hosted at"
      protocol: "https"
      default: "umami.*"
      required: true

services:
  umami:
    container_name: umami
    image: ghcr.io/umami-software/umami:postgresql-latest
    labels:
      - kr.ingress.3000=${INGRESS:-https://umami.*}
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: "fb7@AS*e6xyta!#Mwv!rev*6Z#XMiLj!NKfWzjBFECh66"
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    container_name: umami-db
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    command: |
      bash -c '
      if [[ ! -f /docker-entrypoint-initdb.d/schema.postgresql.sql ]]; then 
        wget https://raw.githubusercontent.com/umami-software/umami/master/sql/schema.postgresql.sql -qO /docker-entrypoint-initdb.d/schema.postgresql.sql
      fi
      exec docker-entrypoint.sh postgres
      '

volumes:
  umami-db-data:
    name: umami-db-data
    driver: "local"

