version: '3.9'
name: kubernetes

x-kraud-ui:
  label: "Kubernetes"
  description: |
    Kubernetes  also known as K8s  is an open-source system for automating deployment, scaling, and management of containerized applications.

  logo_url: "https://kubernetes.io/images/favicon.png"
  ext_url: "https://kubernetes.io"

  config:
    MEM:
      label: "Memory and CPU"
      description: "How much comput power would you like?"
      kind: select
      default: 2G
      options:
        - label: "2 GB / 2 GHz"
          value: "2G"
          description: "2 GB memory, 2Ghz CPU"
        - label: "4 GB / 4 GHz"
          value: "4G"
          description: "4 GB memory, 4Ghz CPU"
        - label: "8 GB / 8 Ghz"
          value: "8G"
          description: "8 GB memory, 8Ghz CPU"
        - label: "16 GB / 16 Ghz"
          value: "16G"
          description: "16 GB memory, 16Ghz CPU"
        - label: "32 GB / 32 GHz"
          value: "32G"
          description: "32 GB memory, 32Ghz CPU"
        - label: "64 GB / 64 GHz"
          value: "64G"
          description: "64 GB memory, 64Ghz CPU"
        - label: "128 GB / 128 GHz"
          value: "128G"
          description: "128 GB memory, 128Ghz CPU"
        - label: "256 GB / 256 GHz"
          value: "256G"
          description: "256 GB memory, 256Ghz CPU"
        - label: "512 GB / 512 GHz"
          value: "512G"
          description: "512 GB memory, 512Ghz CPU"
        - label: "1 TB / 1 THz"
          value: "1T"
          description: "1 TB memory, 1Thz CPU"
        - label: "2 TB / 2 Thz"
          value: "2T"
          description: "2 TB memory, 2Thz CPU"
    BOOT_SIZE:
      label: "Boot Disk Size"
      description: "Size of the initial boot volume. Boot volumes are block storage and can not be shared with other pods."
      kind: select
      default: 20G
      options:
        - label: "5 GB"
          value: "5G"
          description: "5 GB of disk space"
        - label: "10 GB"
          value: "10G"
          description: "10 GB of disk space"
        - label: "20 GB"
          value: "20G"
          description: "20 GB of disk space"
        - label: "40 GB"
          value: "40G"
          description: "40 GB of disk space"
        - label: "100 GB"
          value: "100G"
          description: "100 GB of disk space"
    ZONE:
      kind: zone
      default: uca
      label: "Deployment zone"
      description: "Zone where the deployment and volumes will be created"
      required: true

networks:
  v:
    driver: ipip
    name: bob
    ipam:
      config:
        - subnet: 192.168.0.0/16


volumes:
  k1:
    driver: lv2
    driver_opts:
      size: ${BOOT_SIZE}
      zone: ${ZONE}
  k2:
    driver: lv2
    driver_opts:
      size: ${BOOT_SIZE}
      zone: ${ZONE}
  k3:
    driver: lv2
    driver_opts:
      size: ${BOOT_SIZE}
      zone: ${ZONE}

services:
  k1:
    restart: always
    image: quay.io/kraudcloud/k8s/debian:12
    build: .
    hostname: k1
    volumes:
      - k1:/
    labels:
      - kr.res.mem=${MEM}
      - kr.zone=${ZONE}
    networks:
      v:
        ipv4_address: 192.168.1.0/24


  k2:
    restart: always
    image: quay.io/kraudcloud/k8s/debian:12
    build: .
    hostname: k2
    volumes:
      - k2:/
    labels:
      - kr.res.mem=${MEM}
      - kr.zone=${ZONE}
    networks:
      v:
        ipv4_address: 192.168.2.0/24

  k3:
    restart: always
    image: quay.io/kraudcloud/k8s/debian:12
    build: .
    hostname: k3
    volumes:
      - k3:/
    labels:
      - kr.res.mem=${MEM}
      - kr.zone=${ZONE}
    networks:
      v:
        ipv4_address: 192.168.3.0/24

